import express from "express";import crypto from "crypto";import fs from "fs";import path from "path";import {fileURLToPath} from "url";
const __dirname=path.dirname(fileURLToPath(import.meta.url)),app=express(),PORT=process.env.PORT||10000,DATA=path.join(__dirname,"data.json");
const DEF={settings:{unitPrice:1000,returnPercent:5,businessIncome:0,paymentNumber:"",paymentMethod:"bKash / Nagad / Rocket"},investors:[],transactions:[]};
function load(){try{if(!fs.existsSync(DATA))fs.writeFileSync(DATA,JSON.stringify(DEF));return JSON.parse(fs.readFileSync(DATA,"utf8"))}catch{return structuredClone(DEF)}}function save(x){fs.writeFileSync(DATA,JSON.stringify(x,null,2))}const uid=()=>crypto.randomUUID();
app.use(express.json());app.use(express.static(path.join(__dirname,"public")));
app.get("/api/public",(q,s)=>{let d=load();s.json(d.settings)});
app.post("/api/signup",(q,s)=>{let d=load(),{name,email,phone,password,paymentRef}=q.body,n=Number(q.body.units);if(!name||!email||!phone||!password||!Number.isInteger(n)||n<1||n>100)return s.status(400).json({error:"সব তথ্য সঠিকভাবে দিন। ইউনিট ১–১০০ হতে হবে।"});if(d.investors.some(x=>x.email.toLowerCase()==String(email).toLowerCase()))return s.status(409).json({error:"এই ইমেইল দিয়ে আবেদন আছে।"});let inv={id:uid(),name,email,phone,units:n,investment:n*d.settings.unitPrice,wallet:0,passwordHash:crypto.createHash("sha256").update(password).digest("hex"),paymentRef:paymentRef||"",status:"pending",createdAt:new Date().toISOString()};d.investors.push(inv);d.transactions.push({id:uid(),investorId:inv.id,type:"investment_request",amount:inv.investment,note:"নতুন investment আবেদন",createdAt:new Date().toISOString()});save(d);s.json({ok:true,message:"আবেদন গ্রহণ করা হয়েছে। Admin যাচাই করার পর বিনিয়োগ সক্রিয় হবে।"})});
function auth(q,s,n){let k=process.env.ADMIN_KEY||"CHANGE_THIS_ADMIN_KEY";if(q.headers["x-admin-key"]!==k)return s.status(401).json({error:"Admin authentication required"});n()}
app.post("/api/admin/login",(q,s)=>{let k=process.env.ADMIN_KEY||"CHANGE_THIS_ADMIN_KEY";q.body.key===k?s.json({ok:true}):s.status(401).json({error:"ভুল Admin Key"})});
app.get("/api/admin/data",auth,(q,s)=>s.json(load()));
app.post("/api/admin/settings",auth,(q,s)=>{let d=load(),b=q.body;if(Number(b.unitPrice)<=0||Number(b.returnPercent)<0)return s.status(400).json({error:"সঠিক settings দিন"});d.settings={unitPrice:Number(b.unitPrice),returnPercent:Number(b.returnPercent),businessIncome:Number(b.businessIncome)||0,paymentMethod:b.paymentMethod||"",paymentNumber:b.paymentNumber||""};save(d);s.json({ok:true})});
app.post("/api/admin/investor/status",auth,(q,s)=>{let d=load(),x=d.investors.find(i=>i.id===q.body.id);if(!x)return s.status(404).json({error:"Investor not found"});x.status=q.body.status;save(d);s.json({ok:true})});
app.post("/api/admin/return",auth,(q,s)=>{let d=load(),x=d.investors.find(i=>i.id===q.body.id),a=Number(q.body.amount);if(!x||!Number.isFinite(a)||a<=0)return s.status(400).json({error:"সঠিক তথ্য দিন"});x.wallet+=a;d.transactions.push({id:uid(),investorId:x.id,type:"return_credit",amount:a,note:q.body.note||"Return credit",createdAt:new Date().toISOString()});save(d);s.json({ok:true})});
app.post("/api/admin/transaction",auth,(q,s)=>{let d=load(),x=d.investors.find(i=>i.id===q.body.id),a=Number(q.body.amount);if(!x||!Number.isFinite(a)||a===0)return s.status(400).json({error:"সঠিক তথ্য দিন"});x.wallet+=a;d.transactions.push({id:uid(),investorId:x.id,type:"manual",amount:a,note:q.body.note||"Manual adjustment",createdAt:new Date().toISOString()});save(d);s.json({ok:true})});
app.get("*",(q,s)=>s.sendFile(path.join(__dirname,"public","index.html")));app.listen(PORT,()=>console.log("Running on "+PORT));